POST  http://localhost:3001/jobProvider/register
Content-Type: application/json

{
    "username":"nikil",
    "phone":"1098765432",
    "location":"Dimapur-1"
}

###
GET http://localhost:3001/jobProvider/jobdetails