POST  http://localhost:3001/jobSeeker/register
Content-Type: application/json

{
    "username":"laxmam",
    "pass":"laxman",
    "phone":"9876543210",
    "age":"20",
    "sex":"Male",
    "jobtype":"constuction"
}

###
GET http://localhost:3001/jobSeeker/jobdetails
Content-Type: application/json

{
    "location":"Toluvi Junction Purana Bazar",
    "jobtype":"construction"
}